### ISSUE TITLE
Official Repository

### ISSUE THREAD

**Issue by Bhaal22** [KallistiOS/KallistiOS#1]
Hi,

I am currently working on setting up a development environment for my dreamcast. Is this repo the official one ? or the one on sourceforge is still maintained ?

Thank you.

**Comment by ljsebald** [comment]
The SourceForge one is still the official repo. This is a mirror that is (usually) kept completely up-to-date.

**Comment by Bhaal22** [comment]
Ok I asked because this repo looks more up to date than the sourceforge one.
I will submit a little pull request regarding kos compilation.

Just need to sqash it correctly before.
