### ISSUE TITLE
Parallax/bubbles demo broken

### ISSUE THREAD

**Issue by darcagn** [KallistiOS/KallistiOS#102]
Works on 4.7.4 compiler, but doesn't work on 9.3.0 or 12.2.0. On either of these compilers, one just sees a strip of colors on the left side of the screen.

**Comment by andressbarajas** [comment]
I'll take a stab at this.  Interesting problem for me since we have the same source code but different compilers.

**Comment by andressbarajas** [comment]
Compiling kos and kos-ports using -O0 or -O1 makes the bubbles example work again but.... still some other parallax examples fail to show anything on screen.

**Comment by ljsebald** [comment]
Fixed by #123. Thanks @andressbarajas.
