### ISSUE TITLE
GCC 4.7.4 Doesnt compile on macOS

### ISSUE THREAD

**Issue by andressbarajas** [KallistiOS/KallistiOS#103]
[build-gcc-sh-elf-4.7.4-pass1.log](https://github.com/KallistiOS/KallistiOS/files/10698537/build-gcc-sh-elf-4.7.4-pass1.log)

I think the important portion of the log is:

configure: error: Specified CC_FOR_BUILD doesn't seem to work
mkdir build-x86_64-apple-darwin21.6.0
mkdir build-x86_64-apple-darwin21.6.0/libiberty
Configuring in build-x86_64-apple-darwin21.6.0/libiberty
make[2]: *** [configure-gmp] Error 1
make[2]: *** Waiting for unfinished jobs....

**Comment by darcagn** [comment]
macOS patches were only made for 9.2.0 and 12.2.0, I'll look into 4.7.4 when I get back from vacation next week.

**Comment by andressbarajas** [comment]
@darcagn Looking at the errors in build-gcc-sh-elf-4.7.4/gmp/config.log are oddly similar to:

https://github.com/jbruchon/elks/issues/774

**Comment by darcagn** [comment]
A few days ago I applied the typical macOS patches from 9.3.0/12.2.0, still ended up with that error. While doing a search I also arrived at that same link; changing rm to -rf made the dSYM warnings go away but still never fixed the actual build error.

**Comment by andressbarajas** [comment]
I believe those dSYM errors are a red herring.  It has more do you with errors in the configure logs rather that the build logs.  For example missing  headers are a cause of the error if you look at the configure logs

**Comment by andressbarajas** [comment]
@darcagn Reading discord, I guess we can kill this issue?

**Comment by ljsebald** [comment]
Closed since we're basically not going to be supporting 4.x going forward, it seems like.
