### ISSUE TITLE
GDB doesnt compile in 9.3 or 12.2 toolchains on mac

### ISSUE THREAD

**Issue by andressbarajas** [KallistiOS/KallistiOS#107]
After installing the main parts of the toolchain.  I circled back to utils/dc-chain and "make gdb" in terminal.  Logs are attached.

[build-gdb-12.1.log](https://github.com/KallistiOS/KallistiOS/files/10716476/build-gdb-12.1.log)
[build-gdb-9.2.log](https://github.com/KallistiOS/KallistiOS/files/10716480/build-gdb-9.2.log)

**Comment by andressbarajas** [comment]
https://dcemulation.org/phpBB/viewtopic.php?p=1059172#p1059172
Looks like others had issues and posted a solution.

**Comment by andressbarajas** [comment]
For GDB 9.2 (GCC 9.3) the fixes are:

Add #include <stdlib.h> to 

[Reason is free()]
sim-cpu.c 
sim-core.c
sim-module.c
nrun.c

[Reason is abort()]
sim-engine.c
sim-io.c

Add #include <string.h> to top of:

kos/utils/dc-chain/gdb-9.2/bfd/elf-bfd.h

Reason: https://unix.stackexchange.com/questions/624486/gdb-installed-from-homebrew-on-macos-big-sur-fails-to-load-symbols-from-elf32-i3

**Comment by sizious** [comment]
That means I guess we can put this patch in the Darwin directory? This is done like that for MinGW

**Comment by gyrovorbis** [comment]
> For GDB 9.2 (GCC 9.3) the fixes are, thanks to dcemulation post above:

Is GCC 12.2.0 any different, or have you just not gotten around to trying it? 

Good work, btw!

**Comment by andressbarajas** [comment]
@gyrovorbis Yes, GCC 12.2 is different and Ive tried to fix it but to no avail.  Its been about a week since I last tried.  I'll try again today.

**Comment by andressbarajas** [comment]
*Possible fix* Building GDB 12.1 for Mac. 

--- Intel Mac ---
export CPATH=/usr/local/include
export LIBRARY_PATH=/usr/local/lib

before you

make gdb

--- M1 Mac ---
export CPATH=/opt/homebrew/include
export LIBRARY_PATH=/opt/homebrew/lib 

before you

make gdb

**Comment by DC-SWAT** [comment]
Also need sign GDB binary:
`codesign --sign "-" /opt/toolchains/dc/sh-elf/bin/sh-elf-gdb`

**Comment by cepawiel** [comment]
I made a PR that should fix the issues mentioned here. I checked the binaries afterwards with `codesign --verify sh-elf-gdb` to make sure it applied, but never did run into an issue when they weren't codesigned, so would appreciate another test to make sure it fixes the issue on your systems!

**Comment by ljsebald** [comment]
@andressbarajas Can you confirm whether or not this is fixed with the merging of PR #148?

**Comment by andressbarajas** [comment]
@ljsebald Confirmed this was fixed by merging of PR #148
