### ISSUE TITLE
vmu_pkg and vmu_hdr structs are inconsistent

### ISSUE THREAD

**Issue by Protofall** [KallistiOS/KallistiOS#15]
I accidentally posted this on a mirror, so re-posting here.

<http://gamedev.allusion.net/docs/kos-2.0.0/structvmu__pkg.html>
<http://gamedev.allusion.net/docs/kos-2.0.0/structvmu__hdr.html>

The pkg struct is converted into the hdr struct for easy usage with VMU save files, however almost every variable has a different type or number of elements depending on which struct you look at and usually the pkg vars are larger than the hdr vars. This can cause issues if you make a vmu_pkg struct with a 20 char "app_id" name and try to use it to make a save file, the last 4 chars will be cut off since the header's var is 4 chars shorter.

From what I can tell, this appears to be an oversight of sorts. Maybe they used to be the same, but then an update changed one struct, but not both. I believe the vmu_hdr struct is correct since it is the header format <http://mc.pp.se/dc/vms/fileheader.html>

**Comment by andressbarajas** [comment]
No oversight. Explanation here https://github.com/KallistiOS/KallistiOS/pull/41

**Comment by Protofall** [comment]
Makes sense. All g
