### ISSUE TITLE
Standardize register access/interface

### ISSUE THREAD

**Issue by QuzarDC** [KallistiOS/KallistiOS#151]
All of the various hardware subsystems and drivers need to read/write to registers. Due to them being written by different people at different times, or being brought in from differing origins, they can differ drastically in how they are addressed, defined, or accessed. If this were standardized, any amount of the code would be more readable and serve as better documentation.

The Maple code might be an exemplar of how to go about this:
In https://github.com/KallistiOS/KallistiOS/blob/master/kernel/arch/dreamcast/include/dc/maple.h#L68

We define a base address, then follow it with defines that have the offset of each register from that base:

`#define MAPLE_BASE      0xa05f6c00          /**< \brief Maple register base */
#define MAPLE_DMAADDR   (MAPLE_BASE+0x04)   /**< \brief DMA address register */`

A macros are then defined:
`#define maple_read(A) ( *((vuint32*)(A)) )

/** \brief  Maple memory write macro. */
#define maple_write(A, V) ( *((vuint32*)(A)) = (V) )`

That is used like this:
`maple_write(MAPLE_RESET1, MAPLE_RESET1_MAGIC);`

On the other end of the scale is the video/framebuffer system:
In https://github.com/KallistiOS/KallistiOS/blob/master/kernel/arch/dreamcast/hardware/video.c#L410

We make a pointer to the registers base:
`static vuint32 *regs = (uint32*)0xA05F8000;`

Then set them all by raw offsets to that base with raw magic numbers:
`    /* Blank screen and reset display enable (looks nicer) */
    regs[0x3A] |= 8;    /* Blank */
    regs[0x11] &= ~1;   /* Display disable */`
    
Sort of halfway between is something like https://github.com/KallistiOS/KallistiOS/blob/master/kernel/arch/dreamcast/include/dc/ubc.h#L32 :
`#define BARA (*((vuint32*)0xFF200000))  /**< \brief BARA register. */
#define BASRA (*((vuint8*)0xFF000014))  /**< \brief BASRA register. */`

Here the register addresses are each in a define, but not built off each other, not named as verbosely, and the casting is built-in.

Reading and writing is then handled by inline functions without intermediary macros:
`static inline void ubc_break_data_write(uint32 address) {
    BASRA = 0;      /* ASID = 0 */
    BARA = address;     /* Break address */`
    
    
What I'd propose to proceed would be to choose the best sorts of characteristics from different examples we have (maple seems to be the most well-structured, but might be overkill too). This could go hand in hand with some apparatus in the doxygen/documentation that would help easily view/search these values. Among other things, it would be determining:
- How should we name register ranges, and individual ones? Based on examples it would seem "SUBSYSTEM_BASE" is how many have been done so far: MAPLE_BASE in maple.h or GAPS_BASE in broadband_adapter.c. There are also a number though that go for "SUBSYSTEM_TYPE_BASE" like SPU_RAM_BASE (duplicated in snd_stream.c and snd_iface.c), PVR_RAM_BASE in pvr.h. With this sort of naming, we might rename maple to MAPLE_REGS_BASE. Then individual ones would swap out BASE for the specific register name. So "SUBSYSTEM_REGS_REGNAME".
- How should we name register values/contents and bitwise masks? Certainly this naming should flow from the above, but having the whole reg define be a prefix for each piece of content in it or each mask may be overly verbose.
- How should we go about reading/writing to these? It might make sense to have the maple defines be something along the lines of a globally included macro, with variations for 8 and 16 bit. Could also include bitwise reads/writes to match whatever standard we come up with for defining values/shifts/masks.
- Hows about undefined register spaces? Certainly these have been noted in places where writing to a register is required for operation (like PVR_UNK_00A8 et al) or needs to be defined for proper operation (like unks in packed flashrom blocks). Typically if we have a list of values 1, 4, 8; I'm in favor of listing the '2' even if we don't know what it is. It's, to my mind, like leaving a todo note.

**Comment by QuzarDC** [comment]
I've opened https://github.com/KallistiOS/KallistiOS/pull/150 as a move towards this improvement, specifically over video.c which has some of the stranger and least documented register access.

**Comment by andressbarajas** [comment]
I'll wait for you guys to decide on the format.  Then I'll tackle a module or two applying it.

**Comment by gyrovorbis** [comment]
Sorry, I'm only now really getting around to looking at these register convention proposals. I actually really like the precedence you're establishing with your PVR PR, @QuzarDC. 

Should we like explicitly describe that register convention here, so we can make sure to adhere to it from now on? I'll change my SQ PR to align with it too.

So based on what I'm seeing, each peripheral/device has:
- BASE address define for the starting address of all SFRs
- SFRs are represented as defines for offsets from the base address
- SFRs are accessed via `PERIPHERAL_GET()/PERIPHERAL_SET()` macros, which take an SFR offset macro and add it to the base address
- All macro definitions are prefixed with the peripheral name like `PERIPHERAL_XXX`
- Individual fields within SFRs are not defined separately and their masks/positions are just used directly? (that's fine, just making sure I'm seeing it right)

Anything else I'm missing that we should note?

**Comment by QuzarDC** [comment]
I think ideally the fields would have their own definition as well, with names prefixed by the register they fill. Maple has a good outline of that kind of structure at https://github.com/KallistiOS/KallistiOS/blob/a4eef8d6e62adbf28c89bca8f26422817c9bcfe7/kernel/arch/dreamcast/include/dc/maple.h#L142 or https://github.com/KallistiOS/KallistiOS/blob/a4eef8d6e62adbf28c89bca8f26422817c9bcfe7/kernel/arch/dreamcast/include/dc/flashrom.h#L248 or all the various bitmasks here: https://github.com/KallistiOS/KallistiOS/blob/a4eef8d6e62adbf28c89bca8f26422817c9bcfe7/kernel/arch/dreamcast/include/dc/pvr.h#L872 https://github.com/KallistiOS/KallistiOS/blob/a4eef8d6e62adbf28c89bca8f26422817c9bcfe7/kernel/arch/dreamcast/include/dc/pvr.h#L873.

Part of the reason I didn't propose any specifics for a standard was that there are a lot of mutually exclusive ones in use. It could well be that you always do #define XXX (Value << ShiftDefine) for some sorts and #define XX (Value << StaticValue) works just the same for others, but I'd presume there's some guiding reason behind doing it one way vs the other. And that's just for prospective values.

I didn't mean specifically to throw my full weight behind the PVR schema as normative, but it seemed like the right way to restructure video as there was so much overlap. I do see merits, for instance, of having each register define set to the its absolute address. This would allow individual registers to be easier to fulltext search for. On the other hand, it looks a lot cleaner and makes a lot of sense contextually to just have the offsets from the base range.

So to my mind the basic naming layout would be something like: SYS_SUBSYS_NAME_NAME2_PURPOSE.

SYS would be equivalent to your PERIPHERAL and would likely be something like: PVR, G1, G2, FLASH, BIOS, MAPLE, etc 
SUBSYS would be optional but TA and maybe FB under PVR; LAN, Modem, BBA under G2; each perif type under MAPLE, etc.
NAME is the specific memory range or register being named.
NAME2 would be for when the NAME represents a group with secondary pieces. This could just be a number.
_PURPOSE would be situational for the purpose of describing the data in the define. MASK or SHIFT might go here._

The last is the only one I am very shakey about. This is used, partially, in pvr.h but doesn't seem to match the general structure of definitions elsewhere (which seem to favor having a hex value with the masked bit/s set) like in broadband_adapter.h, Maple, or even elsewhere in pvr.h.
