### ISSUE TITLE
Deprecate or Fix Cooperative Threading

### ISSUE THREAD

**Issue by QuzarDC** [KallistiOS/KallistiOS#163]
In trying to use [examples/dreamcast/libdream/320x240/320x240.c](https://github.com/KallistiOS/KallistiOS/blob/1ea31b794b17c758087938cc97b529428fcf1d53/examples/dreamcast/libdream/320x240/320x240.c) to validate changes to video, I found that it happened to override default the KOS INIT which sets Preemptive mode and defaults to cooperative. This caused a problem where the usleep at the end of the example would never return.

At the very least the functionality of usleep has to be corrected to work in cooperative threading mode. At best, we should have some thorough testing of it to root out other issues and properly support it. As an alternative though, just ditch it.

**Comment by QuzarDC** [comment]
I believe I managed to fix the specific usage of coop mode in the example provided above here: https://github.com/KallistiOS/KallistiOS/pull/164 The issue of testing/fixing/ditching stands though, as it's likely that coop mode still breaks various hardware usages.

**Comment by gyrovorbis** [comment]
I cast my vote to deprecate it.

1) It has been been broken for so long, and I don't see anybody complaining.
2) It complicates the internals, potentially needs serious work to fix, and as you said, will require some testing/validation examples at very least to verify it's fixed and allow us to maintain it
3) There are alternatives. For example, C++20 has brought coroutines, and as newfangled as that is, they actually work on DC and are meant to model that kind of cooperative multitasking. Then we have developers like Kazade in Simulant who have basically rolled their own coroutine implementation.

**Comment by ljsebald** [comment]
Honestly, I'd be on-board with deprecating it at this point, unless someone really has a good reason to keep it around.

I doubt there is much out there that really ever used it (especially in the last 10 years), since it wasn't the default.

**Comment by ljsebald** [comment]
Closed with #176.
