### ISSUE TITLE
Improve stream.drv Sound Driver File Behavior

### ISSUE THREAD

**Issue by darcagn** [KallistiOS/KallistiOS#173]
Currently, the sound driver binary `sound.drv` is included in the KOS tree so that users do not need to build it from source (and, therefore, do not need the ARM compiler/tools installed unless the ARM code is to be modified), but it has created an annoyance for many users in that it shows up in `git status` as a changed file once KOS is compiled, and so it also frequently gets included accidentally in PRs submitted on Github. 

We should come up with a better solution for this situation. 

Firstly, the sound.drv in the tree is 3332 bytes with the md5sum `b18d5e31f1faf34fe3ea8754c94ff946` (unknown which version of compiler tools it was built with), but GCC 8.4.0 and 8.5.0 toolchains reliably produce a binary of 3244 bytes with the md5sum `481d0160dab367afb3bfe5ccd4daa2d8` for myself and other users. Perhaps an initial solution would be to simply update the `stream.drv` file with a newer version with this md5sum, so that the file isn't frequently changing in the first place for anyone on a modern ARM toolchain.

**Comment by darcagn** [comment]
I actually just realized that the `stream.drv` file was accidentally included (and therefore updated to the newer version) in this PR:
https://github.com/KallistiOS/KallistiOS/pull/168

Therefore it doesn't even need to be updated now, but we should discuss if there's a better solution to this nonetheless.

**Comment by sizious** [comment]
That’s a good idea indeed, maybe we could just copy a prebuilt copy if the ARM toolchain isn’t installed? It could be stored in a `build/` directory?

**Comment by QuzarDC** [comment]
My thoughts would be:

1. Move the file over to the dc-chain folder, to be tied to the toolchain version used to build it. (Perhaps utils/dc-chain/arm-precompiled/stream.drv.trailingvername
2. Have the desired version copied (during toolchain install) to an appropriate place that isn't watched by git (perhaps lib/dreamcast/ , addons/lib, loadable, or just its own new folder).
3. Modify or verify that the default makefile's clean to not remove it. This should, perhaps, be controllable by a switch so that if someone really wants to be modifying it, they can more easily.
4. Whenever there is a new arm toolchain available, build a new version to match it. Whenever there is a change to the driver code, rebuild each of the prebuilt versions being provided.
5. This could also be a good point to make the arm toolchain an optional build, as it would only be used to build this file (or a replacement for it).

**Comment by darcagn** [comment]
My big issue with that idea is that if you already have a toolchain installed and you clone the KOS repo, you'll have to manually copy over the driver from the toolchain installer directory. I have a lot of separate KOS directories and this would just create a new pain point. 

Unless we can come up with some reasons the driver is better when compiled with one compiler over another and vice versa, I think this unnecessarily introduces additional complexity, especially when ARM7DI support has been discontinued in GCC after 8.x and 8.x itself is discontinued. So, it won't be anything to update frequently if at all. At this point, I think we should be able to just pick one. 

I think perhaps we should just have an "official" default copy of the driver in tree with one filename, and have it compile to a different filename at build time (which would be in .gitignore) if the ARM compiler is present.

**Comment by QuzarDC** [comment]
> My big issue with that idea is that if you already have a toolchain installed and you clone the KOS repo, you'll have to manually copy over the driver from the toolchain installer directory. I have a lot of separate KOS directories and this would just create a new pain point.
> 
> Unless we can come up with some reasons the driver is better when compiled with one compiler over another and vice versa, I think this unnecessarily introduces additional complexity, especially when ARM7DI support has been discontinued in GCC after 8.x and 8.x itself is discontinued. So, it won't be anything to update frequently if at all. At this point, I think we should be able to just pick one.
> 
> I think perhaps we should just have an "official" default copy of the driver in tree with one filename, and have it compile to a different filename at build time (which would be in .gitignore) if the ARM compiler is present.
> 
> Oh, and to the last point--it's already optional. `make` installs both, `make build-sh4` builds just the SH4 compiler, and `make build-arm` builds just the ARM compiler. Maybe we could also have a discussion if ARM should be removed from the default `make`.
Ahh, didn't realize that the arm toolchain was already at EOL, figured it might be subject to updates.

Ok, in that case yup, same as everyone else, rename the prebuilt, have it copy over.

And yes, I meant optional as in not built with the default make.
