### ISSUE TITLE
basename function missing from libc

### ISSUE THREAD

**Issue by RossComputerGuy** [KallistiOS/KallistiOS#18]
```
PowerDream/kernel/build on  master [!?] 
[I] ➜ make
[  5%] Linking C executable kernel
/opt/toolchains/dc/sh-elf/lib/gcc/sh-elf/4.7.3/../../../../sh-elf/bin/ld: CMakeFiles/kernel.dir/fs/initrd.c.o: in function `initrd_mount':
/home/ross/PowerDream/kernel/fs/initrd.c:19: undefined reference to `_basename'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/kernel.dir/build.make:304: kernel] Error 1
make[1]: *** [CMakeFiles/Makefile2:104: CMakeFiles/kernel.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```
My Dreamcast OS uses KallistiOS to help do a lot of things and in the initrd module it needs the basename function which for some reason is not compiled.

**Comment by ijacquez** [comment]
I did a quick search and I see no reference to `basename`. You may need to port it over.

I took a look at your project and you're rolling with your own version of the C library. If that's the case, it would be wise to either use KallistiOS' (Newlib) implementation or roll your own in your project: `powerdream/libc/src/string.c`.

**Comment by RossComputerGuy** [comment]
Well the powerdream libc is difference since I want to have my own libc for the apps in a separate portion but the kernel does use KallistiOS's newlib.

**Comment by ijacquez** [comment]
Understood.

Did you build the cross compiler by any chance? In the Newlib sources, there should be a `basename` implementation... Check if the tool-chain script you used does any fiddling with disabling/not-compiling `basename`.

**Comment by RossComputerGuy** [comment]
Yes, I compiled the cross compiler. The toolchain file in PowerDream does not mess with basename from newlib.

**Comment by ljsebald** [comment]
Apologies for the very late reply, but apparently I'm not getting notifications of issue reports for some reason. Anyhow, I've just added basename() and the related function dirname() to koslib.
