### ISSUE TITLE
<png/png.h>: No such file or directory.

### ISSUE THREAD

**Issue by SokolerCComputers** [KallistiOS/KallistiOS#19]
Hello! When compiling a project (using DreamSDK), make cannot find include png.h! Even the example does not compile.

(https://user-images.githubusercontent.com/44033147/69899616-caf9bb00-138a-11ea-9504-5ad91acc3c24.jpg)

**Comment by ljsebald** [comment]
Sorry for the late reply, but you need to build the libraries you want out of the KOS ports collection to get the ported libraries.

If it is not installed by default by DreamSDK, you will need to let the person behind it know. We do not maintain DreamSDK.

**Comment by sizious** [comment]
> Hello! When compiling a project (using DreamSDK), make cannot find include png.h! Even the example does not compile.
> 
> (https://user-images.githubusercontent.com/44033147/69899616-caf9bb00-138a-11ea-9504-5ad91acc3c24.jpg)

You just have to install “png” using the “KallistiOS Ports” tan from the DreamSDK Manager tool. DreamSDK uses KOS but isn’t affiliated to KOS in any way.
