### ISSUE TITLE
Opening a file in append mode doesn't seem to work (via dcload)

### ISSUE THREAD

**Issue by Kazade** [KallistiOS/KallistiOS#22]
Try this:

 - `fopen(some_path, "w"); fwrite(...); fclose(...);`
 - `fopen(some_path, "a"); fwrite(...); fclose(...);`

The result is that only the content from the first write appears in the file. Instead of using append, opening with "r+" the second time and seeking to the end of the file allows you to write.

**Comment by andressbarajas** [comment]
Im getting an Assertion when appending to a file I created in /ram/:

Assertion "0" failed at fs_ramdisk.c:313 in `ramdisk_open': Unknown file mode

Attached is an example project to replicate.

[#22.zip](https://github.com/KallistiOS/KallistiOS/files/10712786/22.zip)

**Comment by andressbarajas** [comment]
@Kazade When you get a chance, pull the latest changes and see if they work for you.  Then we can close this 2+ year old issue <3
