### ISSUE TITLE
parallax rotocube and raster_melt examples not working properly

### ISSUE THREAD

**Issue by darcagn** [KallistiOS/KallistiOS#259]
Tested on 9.3.0 and 13.2.0

parallax/rotocube shows a black screen with some red dots at the top.
parallax/raster_melt crashes:

![Screenshot_20230730_202854](https://github.com/KallistiOS/KallistiOS/assets/5105103/ccb27978-c599-4578-af02-fe052ed36865)

**Comment by darcagn** [comment]
raster_melt issue is probably related to this libjpeg issue:
https://github.com/KallistiOS/kos-ports/issues/20

**Comment by andressbarajas** [comment]
The rotocube issue sounds familiar.  Kinda what bubbles example experienced I fixed it: https://github.com/KallistiOS/KallistiOS/issues/102
I have time this weekend to look at it and possible fix it. Fingers crossed.

@Bruceleeto When you have time, lets connect and talk about libjpeg-turbo.  I want to replace the broken libjpeg we have now.

**Comment by Bruceleeto** [comment]
> The rotocube issue sounds familiar. Kinda what bubbles example experienced but I fixed it: #102 I have time this weekend to look at it and possible fix it. Fingers crossed.
> 
> @Bruceleeto When you have time, lets connect and talk about libjpeg-turbo. I want to replace the broken libjpeg we have now.



I don't have the skill and time to do a proper Kos port for it.
https://github.com/Bruceleeto/kos-ports
Think this is the link to my attempt there.
Uses cmake so would probably need to rip that out.

I didn't test it a great deal I just got the lib to build and I then changed the makefile to -libjpeg-turbo... Or something close to that (on phone atm). And raster melt ran. Left it at that.

But yea it builds on my machine fine, no guarantee it works 😂

**Comment by andressbarajas** [comment]
Fixed raster_melt with my kos-port libjpeg PR here: https://github.com/KallistiOS/kos-ports/pull/39

**Comment by darcagn** [comment]
https://github.com/KallistiOS/KallistiOS/assets/5105103/6b682fae-b8c5-42cf-83d4-7dbbb3cc7062

raster melt is working now! So this issue is taken care of! Closing!
