### ISSUE TITLE
kos_setup_script.sh on macOS Catalina 10.15

### ISSUE THREAD

**Issue by vkedwardli** [KallistiOS/KallistiOS#26]
# 1. Build the compiler
Error: `"cp: gcc-8.4.0/ is a directory (not copied)"`
The `cp config.guess config.sub gcc-*/` command is not working, I have to copy the files to `gcc-8.4.0` & `gcc-9.3.0` manually.  

# 2. make build
Error: `fatal error: 'new' file not found`
```
#include <new>
         ^~~~~
```
`libstdc++` had been replaced with `libc++` since 10.9, so now I have to edit the https://github.com/KallistiOS/KallistiOS/blob/dccc475d238aa81c2dc4cccdf6597bfc635fcce3/utils/dc-chain/Makefile#L71 to 
```
CXX := "$(CXX) -stdlib=libc++ -mmacosx-version-min=10.7"
```
in order to link the c++ libraries

# 3. Build KOS
Error: `ext2fs.o: No such file or directory` (or other .o files)
Compiling with 16 cores CPU requires multiple retries (race condition?), but running `make -j 2` can build it successfully.

**Comment by ljsebald** [comment]
I'm not sure who's script kos_setup_script.sh is, but it is certainly not something that is distributed with KOS itself. Unfortunately, you will have to contact the author of that script for more help with it.

That all said, there is someone working on issues with the build on more recent macOS installations, so hopefully there will be a solution to some of the major sticking points on them soon. I'll point that person over here to see if they have any suggestions for you. Unfortunately, I personally don't have a new enough Mac myself to even try these days...

**Comment by vkedwardli** [comment]
Oops sorry for posting it here, since the `kos_setup_script.sh` the first entry point in the wiki, so I hope If it can rescue some macOS googlers in the future.

**Comment by ljsebald** [comment]
There are still a few issues being worked out on recent macOS, as I mentioned before... The one you mentioned about libc++ being one of them. We had to force libstdc++ to get it to compile earlier versions of GCC, so that might be fixed for the newer 9.x version that dc-chain in the repo uses at the moment.

I'm not sure if there are issues specifically with the kos_setup_script.sh though... Perhaps ask on whatever website you found it on?

**Comment by vkedwardli** [comment]
Sure, I found it on https://dcemulation.org/index.php?title=Compiling_KOS_on_OS_X.
I can verify for macOS should be using `libc++` now since `libstdc++` cannot be linked

**Comment by vkedwardli** [comment]
@sizious thanks a lot, I can compile it successfully with my edits, sharing it just in case.
Glad to hear that this had been addressed.

**Comment by sizious** [comment]
@vkedwardli thank you for you feedback. Feel free to share your edits, just to compare with all my work. I'm not a macOS expert and I've lost a lot of time to understand that Apple introduced breaking changes between High Sierra and Mojave/Catalina (basically headers were moved from `/usr/include` to SDK directories).

Have you tried to compile `gdb`? If not, you may try to enter `make gdb` in the `dc-chain` directory. I haven't tested it yet but I'll try in few days.
