### ISSUE TITLE
cpp/gltest example prints errors to console

### ISSUE THREAD

**Issue by darcagn** [KallistiOS/KallistiOS#260]
Tested using GCC 9.3.0 and 13.2.0

Besides these errors, the example seems to work fine. They should still be fixed though.

![Screenshot_20230730_203607](https://github.com/KallistiOS/KallistiOS/assets/5105103/001bc77a-b087-4a9b-9a8a-17682a25c04c)

**Comment by gek169** [comment]
Let this issue be accursed

**Comment by Bruceleeto** [comment]
Replacing the invalid enum in glTexEnvi which I believe is GL_TEXTURE_2D with GL_TEXTURE_ENV should fix this. 
Although I may well be wrong, pretty new to OpenGL. 

That being said, tested it on my end and it worked for me fine and threw no errors.

**Comment by andressbarajas** [comment]
@Bruceleeto You are right.  This PR should fix it: https://github.com/KallistiOS/KallistiOS/pull/399.  At least it does for me.  Also fixes the culling issue.
