### ISSUE TITLE
dreameye/sd example crashes after transfer

### ISSUE THREAD

**Issue by darcagn** [KallistiOS/KallistiOS#262]
Tested using GCC 9.3.0 and 13.2.0
Used an SD card formatted to ext2 with KOS's other SD example

All images transfer successfully to SD, but upon completion the example crashes instead of exiting gracefully.

![Screenshot_20230730_201735](https://github.com/KallistiOS/KallistiOS/assets/5105103/655d1362-6d48-407a-8d9d-95457c054da1)

**Comment by darcagn** [comment]
For more clarity, it's crashing on `fs_ext2_unmount("/sd");`. 
The similar example `sd/ext2fs` makes the same function call and doesn't crash, though.

**Comment by DC-SWAT** [comment]
Maybe it crashes on "free", I've had some problems with that. And not only me.
There is some kind of floating issue with calling "free". But I still can't figure out why.

**Comment by gyrovorbis** [comment]
I get labor day (Monday) off, and I will hopefully have time to look at this one. I hope @DC-SWAT is right, and we can use this to reproduce the issue they were seeing in DreamShell!

**Comment by darcagn** [comment]
> I get labor day (Monday) off, and I will hopefully have time to look at this one. I hope @DC-SWAT is right, and we can use this to reproduce the issue they were seeing in DreamShell!

Agreed. @DC-SWAT, do you have a reproducible example where `free` causes a crash for you? We will help find the problem.

**Comment by DC-SWAT** [comment]
A part of this code not present in repository and lost. I reproduced this when I used dynamic memory [here](https://github.com/DC-SWAT/DreamShell/blob/master/src/fs/fat/dc.c?ts=4#L1106) + [free here](https://github.com/DC-SWAT/DreamShell/blob/master/src/fs/fat/dc.c?ts=4#L1118) and [here](https://github.com/DC-SWAT/DreamShell/blob/master/src/fs/fat/dc.c?ts=4#L913) if used unaligned buffer and requested size more than cluster buffer size. I implement in fatfs contiguous sector reading, as I made it for iso loader firmware, and tried add support it for unaligned buffers and DMA, and got this issues. I had to switch to PIO mode only and it's works good for core and It doesn't affect games, so I left it as is for now.
@megavolt85 experienced a issues with free when modifying the openmenu, maybe it can be easier to reproduce with it.

**Comment by gek169** [comment]
Let this issue be accursed as well
