### ISSUE TITLE
g1ata/atatest example hangs at "Reading 1024 blocks by DMA"

### ISSUE THREAD

**Issue by darcagn** [KallistiOS/KallistiOS#263]
Tested using GCC 9.3.0 and 13.2.0

My SSD connected through a SATA converter works fine in DreamBoot and in DreamShell, I can mount the filesystem, browse files, etc. 

g1ata/atatest detects it, but it hangs indefinitely at `Reading 1024 blocks by DMA`. 
Is this just a problem on my end or is anyone else able to complete g1ata/atatest test successfully with their drive?

**Comment by DC-SWAT** [comment]
You use BBA at same time?
I have the same issue when I run this example through dс-tool-ip

**Comment by darcagn** [comment]
I've tried both with dcload-ip+BBA and with dcload-serial+modem and I get the same problem either way. 
It is currently working for you with dcload-serial?

**Comment by DC-SWAT** [comment]
I found my post in DS discord about this.
The problem is in the logging. If you display the log on screen instead of dc-load, then G1 DMA test works fine.

**Comment by darcagn** [comment]
Thanks! I can confirm you are correct; the example works when outputting to fb.

![Screenshot_20230816_100137](https://github.com/KallistiOS/KallistiOS/assets/5105103/e442e11c-cdc3-49ed-9d25-af44d8052d28)

**Comment by gyrovorbis** [comment]
What in the actual? Yeah, I can reproduce this. But it's kind of weirder.

1) Default config with dbglog(): hangs at reading 1024 blocks by DMA
2) Replace with printf(), no longer hangs, but PIO reads don't match DMA buffer read
3) Redirect dbglog() to "fb": works fine.

**Comment by gek169** [comment]
Let this issue be accursed

**Comment by darcagn** [comment]
I just tried this one again, since there's been a bunch of changes to KOS, and it seems to work fine now. Thanks @DC-SWAT and @gyrovorbis for your help on this one.

**Comment by andressbarajas** [comment]
The curse has been lifted!
