### ISSUE TITLE
libdream/800x608 example gives error "invalid generic mode 1002"

### ISSUE THREAD

**Issue by darcagn** [KallistiOS/KallistiOS#264]
Tested using GCC 9.3.0 and 13.2.0

Example prints error `vid_set_mode: invalid generic mode 1002`.

This is output:
![Screenshot_20230809_141201](https://github.com/KallistiOS/KallistiOS/assets/5105103/a06d6d01-6542-40ab-829b-1277776e7ad0)

`kernel/arch/dreamcast/hardware/video.c` says this video mode is broken:
![Screenshot_20230809_141500](https://github.com/KallistiOS/KallistiOS/assets/5105103/34fe449a-3e2c-43e4-8c85-a37d74a20838)

![image](https://github.com/KallistiOS/KallistiOS/assets/5105103/cf8ae659-00f2-4c99-b5fb-900b22e91248)

So perhaps it should not be a demo?

**Comment by ljsebald** [comment]
The example itself has a comment about things being broken potentially too, so...
```c
/* This sample program shows off 800x608, the mythical "unsupported" video
   mode that Sega will probably complain doesn't work (like they did for
   our 320x240 modes earlier on ;-). This will probably only work on a VGA
   monitor and I highly recommend that you don't try it on a non-multisync.
   Still needs some tweaking.

   In here I also demonstrate how to use the bfont BIOS font routines, and
   how to initialize only selected parts of KOS (resulting in a much
   smaller and less polluted binary).

 */
```

**Comment by gek169** [comment]
Let this issue be accursed

**Comment by andressbarajas** [comment]
Might have no hope of fixing it but we can look at dreamhal video modes and replace them?

https://github.com/sega-dreamcast/dreamhal/blob/3620f5b96af2668d8c065bf78abf219224d236b8/startup/startup_support.c#L689

**Comment by gyrovorbis** [comment]
Can someone make sure we also add a `printf()` to the example that says it's currently not supported properly or something, just so in `v1.2.0`, it doesn't look as broken to the users? Not saying we need to add support for this release, though.

**Comment by gyrovorbis** [comment]
Closing this issue, since we've removed it for now... If we want to track trying to implement it correctly or fix it and bring that back, we can open another issue for it. I think the scope of what this one was capturing is now complete.
