### ISSUE TITLE
<dirent> headers with conflicting declarations

### ISSUE THREAD

**Issue by Corbachu** [KallistiOS/KallistiOS#27]
I'm using <dirent.h> for filesystem handling but it seems my code no longer compiles properly. I updated KOS about two months ago since I was using an old version beforehand. 

The file which is failing to compile in KOS is linked below, and is identical across PC and DC ports:
[filesystem_linux.cc](https://github.com/3dfxdev/EDGE/blob/master/epi/filesystem_linux.cc)

This has always worked without any modifications needed for KOS over the years. I understand if it needs modification for GCC9, but it looks like it is pulling different headers from two different spots (sh-elf and kos-shelf/dirent) which might be formatted differently. Changing, in the fileystem_linux.cc code, the include for <dirent.h> to <sys/dirent.h> stops these errors but then I get undefined references at link time.

I am compiling with WSL2/Debian, Win10 2004(fast insider ring). KOS is as-is pulled from git and up-to-date.

**Build output and errors:**

![dirent-errors](https://user-images.githubusercontent.com/5349851/82766750-49816380-9dd6-11ea-977f-2973fae32c15.png)

I can't tell what is failing where. To note, the PC version uses much of the same filesystem code on new GCC versions as well and does not encounter an issue.

Any advice is greatly appreciated.

**Comment by Corbachu** [comment]
Accidentally pasted the wrong link to the file, in case the update is not seen, here it is:
[filesystem_linux.cc](https://github.com/3dfxdev/EDGE/blob/master/epi/filesystem_linux.cc)

**Comment by ljsebald** [comment]
Pull the latest commit. KOS' <sys/dirent.h> was missing C++ header guards, which seems to be what your errors are about. I've added them in, so it should (hopefully) be fixed now.

**Comment by Corbachu** [comment]
Thanks for fixing this, it’s linking properly again. 👌🏻
