### ISSUE TITLE
lwip examples

### ISSUE THREAD

**Issue by andressbarajas** [KallistiOS/KallistiOS#28]
I believe lwip was removed from kos-ports so there is no way to compile the examples in lwip folder.

**Comment by ljsebald** [comment]
I should probably see what's useful in them and update them to use the built-in stack, rather than just deleting them... I'll add that to my list of things to do...

**Comment by ljsebald** [comment]
The only one that was really still useful was the httpd example, which I've ported over to the built-in stack. So, all the lwIP examples are now gone.
