### ISSUE TITLE
STDIO file redirection does not work

### ISSUE THREAD

**Issue by gyrovorbis** [KallistiOS/KallistiOS#305]
A low priority bug was reported by Ian Michael which I wanted to capture, because it's a perfectly reasonable thing to want to do with KOS and is something that might be an easy fix that just never got looked into.

Anyway, standard C allows you to redirect the standard output file streams like so:
```
#include <stdio.h>

int main(int argc, char* argv[]) {
    // Open a file for writing 
    FILE *output_file = fopen("/pc/output.txt", "w");

    if (output_file == NULL) {
        perror("Error opening output file");
        return 1;
    }

    // Redirect stdout to the output file
    if (freopen("/pc/output.txt", "w", stdout) == NULL) {
        perror("Error redirecting stdout");
        return 1;
    }

    // Now, any text printed using printf will be written to the output file
    printf("This text will be written to the file.\n");
    printf("redirecting printf to a file.\n");

    // Close the output file to flush the data
    fclose(output_file);
    
    return 0;
}
```
However, it seems as though this fails to produce any output to "output.txt" with KOS, as somewhere down the code path stdout/stderr appears to be hardcoded.

**Comment by QuzarDC** [comment]
This is explicitly noted as a TODO: https://github.com/KallistiOS/KallistiOS/blob/master/kernel/fs/fs.c#L367 . I had called it out in https://github.com/KallistiOS/KallistiOS/issues/224 as part of the reason to document fs_pty. To my estimation fs_pty would be better served as an addon, or to just be removed unless there's anyone out there who has ever used it (could never find evidence of that).

It has a separate issue in that /pty/ does not present a '.' in its dir structure, so if allowed in just an open file browser, you'd need to write in explicit support for returning to the previous directory.

**Comment by pcercuei** [comment]
> It has a separate issue in that /pty/ does not present a '.' in its dir structure, so if allowed in just an open file browser, you'd need to write in explicit support for returning to the previous directory.

Honestly this is a problem with half of the VFS, that probably should be fixed.

**Comment by gyrovorbis** [comment]
> > It has a separate issue in that /pty/ does not present a '.' in its dir structure, so if allowed in just an open file browser, you'd need to write in explicit support for returning to the previous directory.
> 
> Honestly this is a problem with half of the VFS, that probably should be fixed.

Agreed. I actually have it in my notes and on my todo list to add that to all of the roots.

**Comment by tavianator** [comment]
In the OP's example, there's no reason to open the file twice.  The intended usage is just `freopen(...)`, and the `fclose()` should not be necessary.

**Comment by gyrovorbis** [comment]
> In the OP's example, there's no reason to open the file twice. The intended usage is just `freopen(...)`, and the `fclose()` should not be necessary.

Gotcha. No idea why I was opening it twice or where I got that from, but the `fclose()` at the end to "flush the buffer" might have been inserted by me, because we used to have a bug where we were not calling the `atexit()` chain properly upon exiting main, so Newlib was never actually flushing the `stdout` buffer... But that's been long-since fixed.

**Comment by andressbarajas** [comment]
@gyrovorbis I think we fixed all the pty related issues.  Double check by getting the latest and trying this again.
