### ISSUE TITLE
PR #329 breaks -flto unless using KOS_INIT_FLAGS(INIT_NET)

### ISSUE THREAD

**Issue by darcagn** [KallistiOS/KallistiOS#336]
For example, when compiling `pvrmark`:

```
$ make
rm -f pvrmark.elf
kos-cc  -c pvrmark.c -o pvrmark.o
kos-cc -o pvrmark.elf pvrmark.o
/opt/toolchains/dc/sh-elf-13.2.0/bin/../lib/gcc/sh-elf/13.2.0/../../../../sh-elf/bin/ld: /tmp/ccA5SDhk.ltrans1.ltrans.o: in function `_dcls_recv_loop':
/opt/toolchains/dc/kos/examples/dreamcast/pvr/pvrmark/../../../../kernel/arch/dreamcast/fs/fs_dclsocket.c:118:(.text.dcls_recv_loop+0x19c): undefined reference to `_abort'
collect2: error: ld returned 1 exit status
make: *** [Makefile:23: pvrmark.elf] Error 1
```

Reverting PR #329 fixes the issue.

**Comment by gyrovorbis** [comment]
Ughghggh. Not having much luck really root-causing this, although you can cheap-assedly fix it just by doing
```
__attribute__((used)) void abort(void) {
    arch_exit();
}
```
in `abort.c`.

**Comment by ijacquez** [comment]
I've experienced this as well with Yaul and LTO. I believe the GCC documentation recommended using the `used` attribute.

**Comment by gyrovorbis** [comment]
> I've experienced this as well with Yaul and LTO. I believe the GCC documentation recommended using the `used` attribute.
Oh snap. That definitely fixed it too... I just wasn't sure if that was a dirty hack or if it was the recommended way to handle it. Thanks for sharing!

**Comment by gyrovorbis** [comment]
PS: @ijacquez Following along with YAUL now. I want to eventually get my VMU emulator on the Saturn! ;)

**Comment by ijacquez** [comment]
> > I've experienced this as well with Yaul and LTO. I believe the GCC documentation recommended using the `used` attribute.
> 
> Oh snap. That definitely fixed it too... I just wasn't sure if that was a dirty hack or if it was the recommended way to handle it. Thanks for sharing!

Just to be sure I wasn't lying, [here](https://gcc.gnu.org/wiki/LinkTimeOptimizationFAQ#Elimination_of_unused_functions) is where I read the suggestion to use the `used` attribute.
