### ISSUE TITLE
Toolchain makefile, init.mk being included before host-detect.mk causes GDB build to fail on msys2/mingw64

### ISSUE THREAD

**Issue by ppxxcc** [KallistiOS/KallistiOS#418]
# Background
I am building under MSYS2, mingw64.
I successfully built the toolchain itself with `make build-sh4`
Now I am trying to build GDB with `make gdb`, but having problems.

# Problem
If you look in the makefile of [dc-chain/Makefile](https://github.com/KallistiOS/KallistiOS/blob/master/utils/dc-chain/Makefile)

you can see that init.mk is included before host-detect.mk.

```
# Initialization rules
include scripts/init.mk

# Detect host machine
include scripts/host-detect.mk
```

host-detect.mk has the following code to detect if running on Windows, and will set the WINDOWS variable.

```
# Determine if we are running under MinGW/MSYS
# This will make difference between MinGW/MSYS and MinGW-w64/MSYS2
ifneq ($(shell echo "$(host_triplet)" | grep -i 'mingw'),)
  is_legacy_mingw=$(shell pacman --version >/dev/null 2>&1 || echo 1)
  ifeq ($(is_legacy_mingw),1)
    $(info MinGW/MSYS build environment detected)
    MINGW := 1
  else
    $(info MinGW-w64/MSYS2 build environment detected)
    MINGW64 := 1
    # config.guess is not reliable in this environment
    host_triplet=$(shell echo $$MSYSTEM_CHOST)
  endif
  MINGW32 := 1
  WINDOWS := 1
endif
```

init.mk has the following code to set the appropriate .exe extension if WINDOWS is defined.
```
# For all Windows systems (i.e. Cygwin, MinGW/MSYS and MinGW-w64/MSYS2)
ifdef WINDOWS
  executable_extension=.exe
endif
```

Here is the issue, these free-standing statements execute in order from top to bottom, and since init.mk is included before host-detect.mk, WINDOWS is never defined in init.mk to set the executable_extension variable.

This causes a failure to build gdb because the makefile script gdb.mk wants to strip the debug symbols, and is using the executable_extension  variable which was never properly defined. Since msys2/mingw64 will put an .exe extension on its executables, this causes strip to not find the executable and it fails.
```
		gdb_run=$(sh_prefix)/bin/$(sh_target)-run$(executable_extension); \
		if test -f $${gdb_run}; then \
			strip $${gdb_run}; \
		fi; \
```

as demonstrated with the following error message:
`C:\MSYS2\mingw64\bin\strip.exe: 'C:/MSYS2/opt/dreamcast/sh-elf/bin/sh-elf-run': No such file`

To demonstrate the point further, putting the following code in gdb.mk shows the problem:
```
ifdef WINDOWS
  ifeq ($(executable_extension),)
    $(info WINDOWS defined but executable extension is empty!)
  else
    $(info WINDOWS defined and executable extension is $(executable_extension))
  endif
endif
```

This outputs the following
`WINDOWS defined but executable extension is empty!` showing that the extension was never set.

# Solution?

However, if you modify the makefile to move the host-detect.mk to happen before init.mk, like
```
# Detect host machine
include scripts/host-detect.mk
# Initialization rules
include scripts/init.mk
```

Then, the gdb.mk will output `WINDOWS defined and executable extension is .exe` as expected.

# Conclusion

In a freshly cloned repository, after moving host-detect.mk to come before init.mk, both `make build-sh4` and `make gdb` successfully complete on msys2/mingw64.

**Is there a reason why the init.mk comes before host-detect.mk?** or is this an oversight because few people might be trying to build the toolchain themselves on msys2/mingw64?

**Comment by darcagn** [comment]
I'll try later and see if this fixes my issue on FreeBSD. Last time I tried it didn't detect the platform properly and executed `make` instead of `gmake`.

**Comment by sizious** [comment]
> Is there a reason why the init.mk comes before host-detect.mk? or is this an oversight because few people might be trying to build the toolchain themselves on msys2/mingw64?

I think this changed at some point as in the past when I did the rewrite (+3 years ago) it was indeed different

Thank you very much for spotting this!

**Comment by sizious** [comment]
OK found the commit changing this:
https://github.com/KallistiOS/KallistiOS/commit/a9ac6f8a5b1cacf8a1ffb98682795853ba16286b

**Comment by sizious** [comment]
> I'll try later and see if this fixes my issue on FreeBSD. Last time I tried it didn't detect the platform properly and executed `make` instead of `gmake`.

Probably the same issue as in the past it was working on BSD

**Comment by darcagn** [comment]
> > Is there a reason why the init.mk comes before host-detect.mk? or is this an oversight because few people might be trying to build the toolchain themselves on msys2/mingw64?
> 
> Thank you very much for spotting this!
> 
> OK found the commit changing this: [a9ac6f8](https://github.com/KallistiOS/KallistiOS/commit/a9ac6f8a5b1cacf8a1ffb98682795853ba16286b)
> 
> This change was made by @cepawiel to add `_download_type` possibility

We discussed it with Colton on Discord a few days ago and he said he doesn't remember why he moved them around, but it was necessary for some reason. So we'll have to do some testing. I haven't gotten around to it yet.

**Comment by cepawiel** [comment]
I just looked into this again and the reason I moved `init.mk` before `host-detect.mk` was due to needing to download the `config.guess` and wanted to reuse the functions. I'd put them into the `init.mk` and swapped the order as I didn't see any issues in my testing but, but should be able to split the download stuff into a separate file and restore the previous include order. I'll make that change and push a branch for testing!

**Comment by cepawiel** [comment]
I believe this Draft PR should fix the issue! @ppxxcc would you be able to confirm if this PR fixes your issues with building GDB on Windows?

**Comment by darcagn** [comment]
> I believe this Draft PR should fix the issue! @ppxxcc would you be able to confirm if this PR fixes your issues with building GDB on Windows?

This fixes the issues with FreeBSD being detected for me. Now I can build the toolchain under FreeBSD (although some unrelated issues are popping up with GDB)
