### ISSUE TITLE
GDB requires workaround to build on FreeBSD

### ISSUE THREAD

**Issue by darcagn** [KallistiOS/KallistiOS#434]
Dropping this here to document until we can properly fix.

GDB doesn't install on FreeBSD out of the box. One needs to use
`sudo CPPFLAGS="-I/usr/local/include" C_INCLUDE_PATH=/usr/local/include LIBRARY_PATH=/usr/local/lib gmake gdb`
to install correctly.

without `C_INCLUDE_PATH` it can't find gmp/mpfr headers and without `CPPFLAGS` it can't find libintl.h header.

**Comment by pcercuei** [comment]
And why do you have that stuff in `/usr/local`?

**Comment by darcagn** [comment]
FreeBSD uses `/usr/local` for components that are not part of the FreeBSD operating system.
GMP, MPFR, and gettext are not part of the FreeBSD operating system, so they are placed in `/usr/local`. :wink:
