### ISSUE TITLE
parallax/bubbles and parallax/rotocube do not work

### ISSUE THREAD

**Issue by darcagn** [KallistiOS/KallistiOS#467]
It shows a black screen, and prints this message:

```
Bubbles Parallax sample: press START to exit, A to toggle sphere type
```

But no button does anything, it's just hung.

Tested on `stable` toolchain with `-O2`.

**Comment by DC-SWAT** [comment]
These examples uses direct render with SQ.
So need fix `plx_dr_init` in `libparallax/include/dr.h`.

```
- #define plx_dr_init(a) pvr_dr_init(*a)
+ #define plx_dr_init(a) pvr_dr_init(a)
```

**Comment by gyrovorbis** [comment]
Okay, I fixed them here: https://github.com/KallistiOS/KallistiOS/pull/474

@DC-SWAT was right, but there were a couple other minor issues going on with the two... One of which was honestly the bubbles example not even really properly using its own parallax APIs and interleaving direct rendering with `pvr_prim()` calls... lol.

**Comment by gyrovorbis** [comment]
Closing this, as it should now be fixed!
