### ISSUE TITLE
clock_gettime(), clock_settime(), and clock_getres() not properly declared in headers

### ISSUE THREAD

**Issue by darcagn** [KallistiOS/KallistiOS#494]
These three functions are defined in `clock_gettime.c`:
https://github.com/KallistiOS/KallistiOS/blob/master/kernel/libc/posix/clock_gettime.c

KOS doesn't declare them anywhere, it's expected that they will be declared in newlib's `time.h` header:
https://sourceware.org/git/?p=newlib-cygwin.git;a=blob;f=newlib/libc/include/time.h;h=ed6cc70fec9469b21fc0217bbe3f5771cdfae23c;hb=26f7004bf73c421c3fd5e5a6ccf470d05337b435#l156

But in that header they are gated behind `#if defined(_POSIX_TIMERS)`, which is actually not defined. The definition of `_POSIX_TIMERS` is in KOS's `time.h` but is commented out:
https://github.com/KallistiOS/KallistiOS/blob/33c7ee5dbacfb0d2e862377da8ffb4ac00818cf1/include/kos/time.h#L48-L51

If we define `_POSIX_TIMERS` for newlib, though, it will also include declarations for  `timer_create()`, `timer_delete()`, `timer_settime()`, `timer_gettime()`, and `timer_getoverrun()`, which we don't have and probably don't have any interest in having as per-process timers.

So perhaps we should include declarations for these in a header somewhere within KOS.

In GCC 13 and earlier, implicit function declarations would just result in a warning, so the functions were still usable, but with GCC 14 coming soon, implicit function declarations will become an error in the near future.

**Comment by QuzarDC** [comment]
Though they wouldn't be useful for ground-up stuff, I could see the per-process timers being useful for posix compatibility generally (and therefore for porting). I would go for the route of properly supporting them rather than hacking around it into KOS.

**Comment by gyrovorbis** [comment]
> Though they wouldn't be useful for ground-up stuff, I could see the per-process timers being useful for posix compatibility generally (and therefore for porting). I would go for the route of properly supporting them rather than hacking around it into KOS.

Yeah, that was actually my first naive thought, not really knowing how they're implemented, but (if I'm recalling correctly), I believe @ljsebald was telling me that the whole thing rides ontop of the POSIX signal system and mechanism which we also don't implement, and is apparently a nontrivial endeavor to add.

Not that I'm against it at all, but given that it's a much bigger task, I was thinking we could start out by just including the declarations outside of Newlib, then later removing those three lines once we do full timer support?

**Comment by QuzarDC** [comment]
> > Though they wouldn't be useful for ground-up stuff, I could see the per-process timers being useful for posix compatibility generally (and therefore for porting). I would go for the route of properly supporting them rather than hacking around it into KOS.
> 
> Yeah, that was actually my first naive thought, not really knowing how they're implemented, but (if I'm recalling correctly), I believe @ljsebald was telling me that the whole thing rides ontop of the POSIX signal system and mechanism which we also don't implement, and is apparently a nontrivial endeavor to add.
> 
> Not that I'm against it at all, but given that it's a much bigger task, I was thinking we could start out by just including the declarations outside of Newlib, then later removing those three lines and adding the `#define` to _properly_ enable them in Newlib once we do full timer support?

Oh no! It absolutely does: https://pubs.opengroup.org/onlinepubs/007904975/functions/timer_create.html requires being able to interact with signal events which is a giant thing. Ok, so I take it back because anything portable that would need it would necessarily be wanting to use signaling which we wouldn't be able to support anyways. So totally on board with just faking that declaration. 

*Maybe* a slightly better way would be to provide stubs for the functions that just have compiler warnings, that way we can just turn on `_POSIX_TIMERS = 1`, so that it'll play nicer with cmake or autotools or such trying to understand we have `clock_` functions but if it needs something we don't have there's warning?

**Comment by gyrovorbis** [comment]
Closing this issue now that https://github.com/KallistiOS/KallistiOS/pull/495 has been merged.
