### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by 7dog123** [KallistiOS/KallistiOS#53]
When building the SDK after compiling the compilers it's missing exports-dreamcast.txt

**Comment by ljsebald** [comment]
There isn't supposed to be an `exports-dreamcast.txt` file anywhere, nor should one be required anywhere.

Did you perhaps configure your environment script incorrectly? I suspect you set `KOS_SUBARCH` to `"dreamcast"` when it should be `"pristine"`, as the comment in the example script says.
