### ISSUE TITLE
issue concerning dc-chain docker image

### ISSUE THREAD

**Issue by maishuji** [KallistiOS/KallistiOS#555]
Hello, 
currently the Dockerfile for the dc-chain is missing a `\` at a command line 39 : 
	
> && make all toolchain_profile=$dc_chain makejobs=$makejobs use_custom_dependencies=1
> 	&& rm -rf /opt/toolchains/dc/kos

Also, I tried to build an image , I got this error using the toolchain_profile=`14.1.1-dev`  ( same issue with 13.2.1 at least):

> gcc/build -I../../gcc-14.1.1/gcc/../include  -I../../gcc-14.1.1/gcc/../libcpp/include  \
>         -o build/genversion.o ../../gcc-14.1.1/gcc/genversion.cc
> g++ -c   -g -O2     -DIN_GCC -DCROSS_DIRECTORY_STRUCTURE   -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Wconditionally-supported -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings  -Wno-error -DHAVE_CONFIG_H  -DGENERATOR_FILE -I. -Ibuild -I../../gcc-14.1.1/gcc -I../../gcc-14.1.1/gcc/build -I../../gcc-14.1.1/gcc/../include  -I../../gcc-14.1.1/gcc/../libcpp/include  \
>         -o build/gengtype-lex.o gengtype-lex.cc
> cc1plus: fatal error: gengtype-lex.cc: No such file or directory
> compilation terminated.
> make[3]: *** [Makefile:2994: build/gengtype-lex.o] Error 1
> make[3]: *** Waiting for unfinished jobs....
> rm gfdl.pod gcc.pod gcov-dump.pod gcov-tool.pod fsf-funding.pod gpl.pod cpp.pod gcov.pod lto-dump.pod
> make[3]: Leaving directory '/opt/toolchains/dc/kos/utils/dc-chain/build-gcc-sh-elf-14.1.1-pass1/gcc'
> make[2]: *** [Makefile:4685: all-gcc] Error 2
> make[2]: Leaving directory '/opt/toolchains/dc/kos/utils/dc-chain/build-gcc-sh-elf-14.1.1-pass1'
> make[1]: *** [Makefile:1047: all] Error 2
> make[1]: Leaving directory '/opt/toolchains/dc/kos/utils/dc-chain/build-gcc-sh-elf-14.1.1-pass1'
> make: *** [scripts/gcc-pass1.mk:13: build-sh4-gcc-pass1] Error 1

**Comment by darcagn** [comment]
Thanks for reporting this. I have PRed a fix for both issues.
