### ISSUE TITLE
Begin releasing versions?

### ISSUE THREAD

**Issue by kallisti5** [KallistiOS/KallistiOS#57]
As a package maintainer, i'd like to see KallistiOS begin releasing versions to ease the packaging process.

I'm mostly interested in making a kallistios_utils-1.0.0 (or whatever) package with tools like scramble, makeip, genromfs, wav2adpcm, vqenc, dcbumpgen, etc.

The idea is simplifying availability of these tools will increase the ease of releasing dreamcast software, and being able to build it without cloning all of KallistiOS and setting up a full SDK.

**Comment by sizious** [comment]
Hello,
What do you mean exactly, you want to have binary releases of KallistiOS utilities coming from the `utils` directory?
BR
Mike

**Comment by kallisti5** [comment]
just start tagging release versions in git.  That will produce archives which can be downloaded.

aka... tag v1.0, package maintainers then can download "stable" versions of the source code to build.

**Comment by ljsebald** [comment]
The repository is tagged and has had releases on SourceForge, which is where it is primarily hosted (per the README and the little blurb at the top of the repository here). Yes, there haven’t been any in a while, but there have been releases there.
