### ISSUE TITLE
Examples broken in legacy (9.3.0) toolchain due to required language features

### ISSUE THREAD

**Issue by QuzarDC** [KallistiOS/KallistiOS#579]
The example /dreamcast/basic/breaking fails to build due to using c2x language features that just don't seem to be implemented in 9.3.0. Should be able to slightly rewrite it to have it drop down to c17 which should be supported fine.
![image](https://github.com/KallistiOS/KallistiOS/assets/686781/f13c151c-dfe5-496f-b110-e2d67f0c5249)

And /dreamcast/cpp/concurrency similarly fails but at the declaration of `-std=c++20` 
![image](https://github.com/KallistiOS/KallistiOS/assets/686781/335b2d98-ee6a-4feb-8879-67cf995ba9fe)

My guess is that this one was never noticed because by default the cpp examples don't build automatically with the rest. 

With the updates to the way we build examples to allow failures, these are less of an issue. If either *needs* the language features then we should at least give a friendlier warning/error for our gcc9 users.

**Comment by gyrovorbis** [comment]
C++ concurrency 100% needs to be C++20, since that's when coroutines and a bunch of the other stuff that's being tested there was added to the standard library.

The other one doesn't need to be C23.

Either way, I can do something more graceful than just failing flat-out, so this is fair.

**Comment by gyrovorbis** [comment]
@cepawiel We can close this now, can't we?

**Comment by QuzarDC** [comment]
These were addressed by #591 .
