### ISSUE TITLE
Can No Longer Compile

### ISSUE THREAD

**Issue by godreborn** [KallistiOS/KallistiOS#651]
I was going to compile sonic mania decompilation for dreamcast, but my old toolchain doesn't have cmake, which I think needs a newer version of the toolchain.  however, running make all results in make command not found in config file.  it doesn't understand curl and wget either.  I don't understand what the problem is, but it's only when using make all in dc-chain.  I'm unable to install any of the new toolchain for some reason.  a lot of files have changed or are missing compared with the newer toolchain.  I can compile sm64 with it, but it uses normal make.  please help.  thanks.

**Comment by andressbarajas** [comment]
What is your OS?
Link to repo or codebase?

**Comment by gyrovorbis** [comment]
OOPS. Sorry, I forgot to respond to this issue as well. Can you also give us the exact errors? Sounds like you should probably just nuke your KOS environment and toolchains and start over fresh with the Dreamcast.wiki tutorial.

**Comment by godreborn** [comment]
I couldn't get it to work at all in ubuntu 20.04 wsl, but it compiled in ubuntu 22.04 wsl, sorta.  I got an error here, when building kos-ports: 

![image](https://github.com/KallistiOS/KallistiOS/assets/13548481/989cd429-397d-46b5-a9a8-eed53dfd6f61)

**Comment by godreborn** [comment]
manually trying to compile it directly results in this: 

![image](https://github.com/KallistiOS/KallistiOS/assets/13548481/1893cce1-7a30-4a41-b190-f855c9df3b37)

**Comment by gyrovorbis** [comment]
The only issue that I'm aware of with building the entirety of KOS and KOS-ports is just damn `libjimtcl` on Windows... I don't expect it to build. This is a known issue: https://github.com/KallistiOS/kos-ports/issues/42.

We're coordinating with the maintainer of `libjimtcl` to fix it; however, dude doesn't have Windows to even test with it, so it's probably going to be slow going until one of us gets time to step up and offer a fix to him.

BUT ON THE OTHER HAND, you're using WSL with Ubuntu, not MSYS to build this? WTF? I would totally expect this to build fine...

The good news is that unless you want to be playing with the TCL scripting language on the Dreamcast with KOS, this can be safely ignored. It's not used internally or by any other library, and eventually we should be able to get a fix for it.

**Comment by godreborn** [comment]
yeah, I usually try to build in wsl, since it's easier for certain systems than windows due to missing commands and whatnot.  I compiled the examples, but I got another error: 

![image](https://github.com/KallistiOS/KallistiOS/assets/13548481/c834d23e-d555-4bfa-b231-c0b4efb402fd)

and, this is the error I get in ubuntu 20.04 for compiling in general:

![image](https://github.com/KallistiOS/KallistiOS/assets/13548481/b9e91575-13aa-4335-bada-79d60293aae7)

thanks for the response btw.

**Comment by gyrovorbis** [comment]
> yeah, I usually try to build in wsl, since it's easier for certain systems than windows due to missing commands and whatnot. I compiled the examples, but I got another error:
> 
> ![image](https://private-user-images.githubusercontent.com/13548481/345522079-c834d23e-d555-4bfa-b231-c0b4efb402fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNTA5MDcsIm5iZiI6MTcyMDA1MDYwNywicGF0aCI6Ii8xMzU0ODQ4MS8zNDU1MjIwNzktYzgzNGQyM2UtZDU1NS00YmZhLWIyMzEtYzBiNGVmYjQwMmZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDIzNTAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1ZDIyNzcxMjAyYTFlMDdhOWI2ODRmYmUyMTJiMGExM2I3NzY5YzEyMDM3MjY0MDkxMTQ4ZjQwZTI1ZjIwODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7CyH56YMqVv0h9iAeX3g7-bwbfL4WoB8-rrF3TrdWRU)

OH, SHIT. We literally just added this example like a day or two ago, and it looks like this is an actual build issue! Fixing it right this minute!

> 
> and, this is the error I get in ubuntu 20.04 for compiling in general:
> 
> ![image](https://private-user-images.githubusercontent.com/13548481/345522716-b9e91575-13aa-4335-bada-79d60293aae7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNTA5MDcsIm5iZiI6MTcyMDA1MDYwNywicGF0aCI6Ii8xMzU0ODQ4MS8zNDU1MjI3MTYtYjllOTE1NzUtMTNhYS00MzM1LWJhZGEtNzlkNjAyOTNhYWU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDIzNTAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4MTZhYmExN2FhNmFjMDAwMmVkOTJiYWRjNjA5MTdkYmQ5M2U0OWVhZWUwZjcwMzJlZjRmYjkyMTIzMzAyOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GRBHuVgC4h-Q4yz7rNo_bk4gi9Ozf40gtHH6YQae3Wc)
> 

WOW. Ubuntu 20 doesn't ship with freaking MAKE? Looks like all you need to do is install the dependencies for Ubuntu mentioned here: https://dreamcast.wiki/Getting_Started_with_Dreamcast_development before trying to build and use the KOS environment.

> thanks for the response btw.

Absolutely! I'll keep you updated on `libjimtcl`, @andressbarajas will let you know when his `pty` example is fixed, and let us know if the Ubuntu 20 build works with WSL once you have installed the dependencies!

**Comment by gyrovorbis** [comment]
Okay, the `pty` example issue has been fixed! OUR BAD!

**Comment by godreborn** [comment]
thanks.  do I just rerun make or make clean or something for the examples or do I have to start all the way over?  also, I have make, curl, and wget installed already on ubuntu 20.04.  I have no idea why it's displaying that error.  I regularly use make in fact in ubuntu 20.04, because it usually seems to be the most versatile distro on the microsoft store, so it's my main distro.

**Comment by gyrovorbis** [comment]
> thanks. do I just rerun make or make clean or something for the examples or do I have to start all the way over? also, I have make, curl, and wget installed already on ubuntu 20.04. I have no idea why it's displaying that error. I regularly use make in fact in ubuntu 20.04, because it usually seems to be the most versatile distro on the microsoft store, so it's my main distro.

Okay, so when we fix something or you want to change something, you cd into the root of the KOS repo, do a pull, a clean, and then a make:
```
cd /opt/toolchains/dc/kos
git pull
make clean
make
```
Then KOS should be rebuilt, and you can go back and try to build the examples again. Nah, you don't have to start all the way over. Super easy to update KOS if you've already set up the repo.

**Comment by gyrovorbis** [comment]
I thought the error on Ubuntu 20 was saying you don't have `make` installed? Try typing `make` without even doing anything KOS-related.

**Comment by godreborn** [comment]
ah, I just saw your edit.  I was about to respond, saying make was working fine.  I've seen errors like this before, but not too often. 
 I was never able to solve them.  I have five distros plus windows in case there's a distro-specific issue, such as that one.

![image](https://github.com/KallistiOS/KallistiOS/assets/13548481/7237da10-7d18-4d45-9e54-3d3dea63121c)

btw, the examples have successfully compiled.  thanks again.

**Comment by gyrovorbis** [comment]
Is it possible that your `Makefile.cfg` got screwed up on Ubuntu 20? cd into `dc-chain` and do a `git checkout Makefile.cfg` to revert it back, then try to `make` again?

**Comment by godreborn** [comment]
somewhat off topic, but I've been rebuilding the toolchain in order to build sonic mania for the dreamcast.  however, no matter what I do it doesn't boot in an emulator.  is it possible it doesn't work in an emulator, only hardware?  I think I've encountered this with the ps3 and the original xbox, but I don't have a console to test it on.  I have 1ST_READ.BIN, IP.BIN, and the data.rsdk in the cdi image, so I'm not really sure.  no errors, and the apps say it's fine.  if you convert an elf to a 1ST_READ.BIN, will it work with any elf file?  I'm trying to figure out if it's the elf that's the problem or cdi4dc.  thanks for the help.

**Comment by gyrovorbis** [comment]
> somewhat off topic, but I've been rebuilding the toolchain in order to build sonic mania for the dreamcast. however, no matter what I do it doesn't boot in an emulator. is it possible it doesn't work in an emulator, only hardware? I think I've encountered this with the ps3 and the original xbox, but I don't have a console to test it on. I have 1ST_READ.BIN, IP.BIN, and the data.rsdk in the cdi image, so I'm not really sure. no errors, and the apps say it's fine. if you convert an elf to a 1ST_READ.BIN, will it work with any elf file? I'm trying to figure out if it's the elf that's the problem or cdi4dc. thanks for the help.

Mephiles actually figured out the issue in the RSDK Discord sever: `KOS_INIT_FLAGS()` was missing `INIT_CDROM`. This wasn't a flag in old KOS and was automatically always compiled-in. So it looks like SonicFreak is using a slightly older version of KOS while we're all using a slightly newer version of KOS. 

Anyway, feel free to hit me up on DIscord, and we'll get the rest sorted out regarding Sonic Mania!
