### ISSUE TITLE
KOS examples issues

### ISSUE THREAD

**Issue by andressbarajas** [KallistiOS/KallistiOS#654]
I found issues with the following examples.  Most of them have on exit issues.  Forgive the formatting, I will fix later:

KOS_CFLAGS:
 -O2 -fomit-frame-pointer -fno-builtin -m4-single-only -ml -ffunction-sections -fdata-sections -matomic-model=soft-imask -ftls-model=local-exec -D__DREAMCAST__  -I/opt/toolchains/dc/kos/include -I/opt/toolchains/dc/kos/kernel/arch/dreamcast/include -I/opt/toolchains/dc/kos/addons/include -I/opt/toolchains/dc/kos-ports/include -D_arch_dreamcast -D_arch_sub_pristine -Wall -g

1. exec Seg fault: (DCLOAD IP ONLY)
maple: attached devices:
  A0: Dreamcast Controller           (01000000: Controller)
  C0: Dreamcast Mouse                (00020000: Mouse)
  D0: Keyboard                       (40000000: Keyboard)

Hello world from the exec.elf process
sub.bin mapped at 8c033c70, jumping to it!

arch: shutting down kernel
maple: final stats -- device count = 3, vbl_cntr = 4, dma_cntr = 4
vid_set_mode: 640x480IL NTSC with 1 framebuffers.
fs_romdisk: unmounting image at 0x8c033bf0 from /rd
Obviously bad packet, avoiding segfault
make: *** [run] Segmentation fault: 11

2. mmu/nullptr freeze (DCLOAD IP ONLY)

**Comment by andressbarajas** [comment]
@QuzarDC @gyrovorbis I updated the list to remove the issues fixed by PR #660.

**Comment by andressbarajas** [comment]
@QuzarDC I updated the list to remove issue fixed by PR #667

**Comment by pcercuei** [comment]
>     2. mmu/nullptr freeze (Seems to be dcload-ip only?)

dcload-ip seems to have problems with MMU usage, yes.
Related ticket: https://github.com/sizious/dcload-ip/issues/22

**Comment by andressbarajas** [comment]
Closing this issue now that the only remaining examples are broken when uploaded using dcload-ip.  So they are dcload-ip issues and not example issues.
