### ISSUE TITLE
Romdisk issue : undefined reference _romdisk_data (using cmake)

### ISSUE THREAD

**Issue by maishuji** [KallistiOS/KallistiOS#666]
Hello, 
I' m not able to link romdisk anymore following kos update
Failed build can be found here : 
https://github.com/maishuji/dreamcast-in-devcontainer-example/actions/runs/9834310279/job/27145902985?pr=1
The issue is 

> undefined reference to `romdisk_data'

I tried to change _extern uint romdisk_ by _extern const uint romdisk_data_ in the main cpp, but still same issue, can you check this issue ? thanks !

I put bellow the logs : 

> -- The CXX compiler identification is GNU 14.1.1
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: /opt/toolchains/dc/kos/utils/build_wrappers/kos-c++ - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Configuring done (0.2s)
> -- Generating done (0.0s)
> -- Build files have been written to: /__w/dreamcast-in-devcontainer-example/dreamcast-in-devcontainer-example/build
> [ 20%] Generating romdisk.img
> 0    rom 1720418368       [0xffffffff, 0xffffffff] 37777777777, sz     0, at 0x0     
> 1    .                    [0x811     , 0x873f7   ] 0040755, sz     0, at 0x20    
> 1    ..                   [0x811     , 0x873f4   ] 0040755, sz     0, at 0x40     [link to 0x20    ]
> 1    default.txf          [0x811     , 0x873f8   ] 0100755, sz  9196, at 0x60    
> [ 40%] Generating romdisk_tmp.c
> [ 60%] Building CXX object src/clock_example/CMakeFiles/clock-example.dir/clock.cpp.obj
> [ 80%] Linking CXX executable clock-example.elf
> /opt/toolchains/dc/sh-elf/lib/gcc/sh-elf/14.1.1/../../../../sh-elf/bin/ld: /opt/toolchains/dc/kos/lib/dreamcast/libromdiskbase.a(romdiskbase.o):/opt/toolchains/dc/kos/kernel/romdisk/romdiskbase.c:11:(.data.__kos_romdisk+0x0): undefined reference to `romdisk_data'
> collect2: error: ld returned 1 exit status
> make[2]: *** [src/clock_example/CMakeFiles/clock-example.dir/build.make:105: src/clock_example/clock-example.elf] Error 1
> make[1]: *** [CMakeFiles/Makefile2:115: src/clock_example/CMakeFiles/clock-example.dir/all] Error 2
> make: *** [Makefile:91: all] Error 2

**Comment by andressbarajas** [comment]
In your makefile, add KOS_ROMDISK_DIR under objects in your make file like you see here: https://github.com/KallistiOS/KallistiOS/blob/86190e3414b9793843d777594dd4754f43278d95/examples/dreamcast/2ndmix/Makefile#L9. Also remove those 2 extern romdisk lines from your main.c or whatever.

**Comment by maishuji** [comment]
I'm using cmake , so no makefile on my project. I removed the extern in the main, still same issue.
In the cmake, I call the cmake kos_add_romdisk like this: 
a ROMDISK_DIR is required in the signature
```
# ---- ROMDISK generation ----
set(ROMDISK_DIR "romdisk")
kos_add_romdisk(${TARGET_NAME} ${ROMDISK_DIR})
```

**Comment by andressbarajas** [comment]
I dont use cmake so I dont know how to help :^/ Maybe use KOS_ROMDISK_DIR instead of ROMDISK_DIR?

**Comment by gyrovorbis** [comment]
[Alrighty closing this one since the was merged. https://github.com/KallistiOS/KallistiOS/pull/677
