### ISSUE TITLE
KOS_CC_BASE is defined with wrong value

### ISSUE THREAD

**Issue by maishuji** [KallistiOS/KallistiOS#669]
Here, it is a directory : https://github.com/KallistiOS/KallistiOS/blob/3f86969c5d4a0846a532823a208ea95a94879897/environ_base.sh#L22 
But here , it is defined as a /../sh-elf command : https://github.com/KallistiOS/KallistiOS/blob/3f86969c5d4a0846a532823a208ea95a94879897/doc/environ.sh.sample#L53

**Comment by darcagn** [comment]
But `/opt/toolchains/dc/sh-elf` is a directory. It's the standard directory where the SH toolchain is installed when using the `${KOS_BASE}/utils/dc-chain` makefile utility to install the SH toolchain.

<img width="396" alt="image" src="https://github.com/KallistiOS/KallistiOS/assets/5105103/37d21900-d35b-459e-9b6e-5b109c6f01ca">

**Comment by maishuji** [comment]
Ah yes, sorry, I misunderstood the code😓

**Comment by darcagn** [comment]
No problem! Thanks for reporting anyway 😄
