### ISSUE TITLE
GLdc Feature Request: Matcap/Spheremap texture support

### ISSUE THREAD

**Issue by EGAMatsu** [KallistiOS/KallistiOS#676]
TLDR, I am making a engine, and on PC it heavily will use Spheremaps, I kinda need them to finish and resume DC support, these need to be supported:

GL_TEXTURE_GEN_S, GL_TEXTURE_GEN_T

Example use:
```c++
glTexGeni(GL_S, GL_TEXTURE_GEN_MODE, GL_SPHERE_MAP);
glTexGeni(GL_T, GL_TEXTURE_GEN_MODE, GL_SPHERE_MAP);
glEnable(GL_TEXTURE_GEN_S);
glEnable(GL_TEXTURE_GEN_T);

// Insert render code here (glBegin() .. glEnd())

glDisable(GL_TEXTURE_GEN_S);
glDisable(GL_TEXTURE_GEN_T);
```

**Comment by darcagn** [comment]
I would recommend opening this issue over at the GLdc repo so it can be tracked properly: https://gitlab.com/simulant/GLdc
