### ISSUE TITLE
LibGL not working?

### ISSUE THREAD

**Issue by Bruceleeto** [KallistiOS/KallistiOS#681]
Tried running a few of the  examples on my Dreamcast, got no output. Pressing Start wouldn't dump me back to the screen either so I had to reboot my console. 

Asked on Simulant about it and another dude had the same issue. 

Examples I tried.

Nehe02
quadmark
Trimark
tristripmark

Trying the elfs on lxdream-nitro  just gave me pvr_dma: "Failed DMAOR check"

**Comment by gyrovorbis** [comment]
Can you verify this is fixed now?

**Comment by Bruceleeto** [comment]
tested the 4 examples above seem to work  on dreamcast and on lxdream  as expected now.
