### ISSUE TITLE
Missing a lock release before returning

### ISSUE THREAD

**Issue by ryancaicse** [KallistiOS/KallistiOS#72]
Hi, a lock release is missed before returning -1. Should it be a bug?
https://github.com/KallistiOS/KallistiOS/blob/525cbdac17317acfc2e4937e2efd7b99c85e73a3/kernel/thread/tls.c#L132-L140

**Comment by ljsebald** [comment]
Yes, that is definitely a bug. Good catch.

I’ll patch that later today.

**Comment by ljsebald** [comment]
Should be fixed in 02c5acc.
