### ISSUE TITLE
Make fails due to flex version.

### ISSUE THREAD

**Issue by nthhhhhhh** [KallistiOS/KallistiOS#73]
On Ubuntu 21.10 and 22.04, when making the toolchain, I have been able to reproduce this error by having the package `flex` installed.

`checking for bison... bison -y
checking for flex... flex
checking lex output file root... configure: error: cannot find output from flex; giving up
make[2]: *** [Makefile:4234: configure-gmp] Error 1
make[2]: Leaving directory '/opt/toolchains/dc/kos/utils/dc-chain/build-gcc-sh-elf-4.7.4'
make[1]: *** [Makefile:856: all] Error 2
make[1]: Leaving directory '/opt/toolchains/dc/kos/utils/dc-chain/build-gcc-sh-elf-4.7.4'
make: *** [scripts/gcc-pass1.mk:16: build-sh4-gcc-pass1] Error 1`

However, running make again with the package `flex-old` fixes the error.

**Comment by ljsebald** [comment]
This is unfortunately one of the pitfalls of using older versions of GCC and the like. This probably should be documented in the site, but alas there isn't much we can do to fix it.
