### ISSUE TITLE
v2.1.0 Release Blockers

### ISSUE THREAD

**Issue by Kazade** [KallistiOS/KallistiOS#743]
This issue is to track bugs and PRs that are blocking the release. Please respond in the comments with suggestions for fixes that should go in.

### Pull Requests

 - [ ] https://github.com/KallistiOS/KallistiOS/pull/727
 - [ ] https://github.com/KallistiOS/KallistiOS/pull/749
 - [ ] https://github.com/KallistiOS/KallistiOS/pull/748
 
### Issues

 - [ ] https://github.com/KallistiOS/KallistiOS/issues/744
 - [ ] https://github.com/KallistiOS/KallistiOS/issues/745

**Comment by gyrovorbis** [comment]
The only actual non-documentation thing I'm aware of ATM is the performance regression introduced by making `pvr_prim()` lock and unlock the SQ mutex every call... Addressed in this PR: https://github.com/KallistiOS/KallistiOS/pull/740

**Comment by andressbarajas** [comment]
Tonight I'm going to update the aica memcpy to copy 4 bytes instead of one each iteration. That can be tested in the new dev branch with GTA3 and then make it into 2.1.0? I'm not home otherwise I would do it right now. Anyone feel free to do that change and don't forget to also include the new stream.dvr.prebuilt

**Comment by andressbarajas** [comment]
@Kazade As I said in #745, lets leave this for 2.2.0+.  I expect it was working fine when I tested it earlier but SKMP let me know that the AICA can handle unaligned memory access.  I was expecting the same exception behavior that he SH4 has.

**Comment by pcercuei** [comment]
@andressbarajas that's not a fix though, is it?

**Comment by andressbarajas** [comment]
Nope, its not. Doubt it's gonna make it in 2.1.0.

**Comment by pcercuei** [comment]
https://github.com/KallistiOS/KallistiOS/pull/751 is a bugfix, it should probably be included.

**Comment by andressbarajas** [comment]
@Kazade This can be closed too.

**Comment by QuzarDC** [comment]
I had communicated as much on the discord in different ways, but even by the time this was created the only blocker was the documentation, as the full rounds of functional and build testing had been completed weeks prior.

Thank you @Kazade for the effort and my apologies for not having kept in sync as well as I could have.
