### ISSUE TITLE
Fix pvr_prim performance regression

### ISSUE THREAD

**Issue by Kazade** [KallistiOS/KallistiOS#744]
@gyrovorbis  has reported a performance regression introduced by making pvr_prim() lock and unlock the SQ mutex every call. 

This is fixed in a more wide-reaching PR (https://github.com/KallistiOS/KallistiOS/pull/740/files) but it would be good to cherry-pick the code necessary to just avoid the perf regression before the 2.1.0 release.

**Comment by gyrovorbis** [comment]
Will get a new PR made tonight with the performance regression fixe﻿s isolated from hybrid submission mechanism... the fix also necessitates the +20% speed/throughput buff too, so that's nice. lol.

**Comment by gyrovorbis** [comment]
Fixed: https://github.com/KallistiOS/KallistiOS/pull/740.
