### ISSUE TITLE
Improve the performance of AICA memcpy

### ISSUE THREAD

**Issue by Kazade** [KallistiOS/KallistiOS#745]
@andressbarajas reported that things can be improved by copying 4 bytes at a time. It would be nice to get this into 2.1.0.

**Comment by andressbarajas** [comment]
@Kazade Probably wont make it to 2.1.0.  I thought everything was working well because I wasnt having issues but SKMP let me know that the AICA wont error out like it does for SH4.  So lets this not be a block for 2.1.0.

**Comment by andressbarajas** [comment]
Okay, changes are in. I tested they work.  Waiting on others to test with GTA 3 for confirmation.

**Comment by andressbarajas** [comment]
@Kazade We can close this one.
