### ISSUE TITLE
examples/mruby/dreampresent build fail

### ISSUE THREAD

**Issue by Tchan0** [KallistiOS/KallistiOS#811]
page_data.rb:279:19: dynamic constant assignment
page_data.rb:280:13: dynamic constant assignment
page_data.rb:293:14: dynamic constant assignment
page_data.rb:294:14: dynamic constant assignment
page_data.rb:295:16: dynamic constant assignment

Apparently happens because constants cannot be defined inside a method: https://saaslit.com/blog/ruby/ruby-constants

Easy to solve, but I'll leave that up to somebody with knowledge of Ruby ( @sizious  ? )

**Comment by gyrovorbis** [comment]
Hah. Is this some Ruby stuff? @Tchan0 knows the Rubies!? Awesome, thanks for reporting!

**Comment by gyrovorbis** [comment]
Should be good to go. Tested and merged the fix. If I'm wrong somehow, please feel free to reopen!
